# migration configuration
---
source-system-name: magento2
destination-system-name: prestashop17
root-category-id: 2
root-category-language: it
additional-categories:
  -
    category-id: 26
    category-language: de
categories-mapping-file: /home/david/workspace_alphaconcept/migration_tool/ecommerce-migration-tool/src/main/resources/config/category-mapping.properties
category-ids-merging-ignore-list:
  - 53
  - 127
  - 128
  - 126
  - 78
category-ids-skipping:
#  - 50